# Lez 2

In [1]:
import numpy as np

## Q1: Fun with arrays

**A.**  Create the array: 
```
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]
```
with out explicitly typing it in.

Now create a new array containing only its 2nd and 4th rows.


**B.** Create a 2d array with `1` on the border and `0` on the inside, e.g., like:
```
1 1 1 1 1
1 0 0 0 1
1 0 0 0 1
1 1 1 1 1
```

Do this using array slice notation to let it work for an arbitrary-sized array

In [2]:
a = np.arange(1,16).reshape(3,5).T
a

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [3]:
a_new = a[1:4:2]
a_new

array([[ 2,  7, 12],
       [ 4,  9, 14]])

In [4]:
c = 10 #colums
r = 5  #rows
b = np.zeros((r,c),dtype=int)

b[0]    = 1
b[-1]   = 1
b[:,0]  = 1
b[:,-1] = 1
b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [5]:
# different approach
b = np.ones((r, c), dtype=int) 

b[1:-1, 1:-1] = 0  

b

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 0, 0, 0, 0, 0, 0, 0, 0, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

## Q2: Histograms

Here we will read in columns of numbers from a file and create a histogram, using NumPy routines.  Make sure you have the data file
"`sample.txt`" in the same directory as this notebook. You download it from  https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt. 
  
  * Use python to download a file! Check out the `requests` package

  * Use `np.loadtxt()` to read this file in.  

  * Next, use `np.histogram()` to create a histogram array.  The output returns both the count and an array of edges.
  
  * Finally, loop over the bins and print out the bin center (averaging the left and right edges of the bin) and the count for that bin.

In [6]:
import requests

response = requests.get("https://raw.githubusercontent.com/sbu-python-summer/python-tutorial/master/day-3/sample.txt")

# save the file
with open('sample.txt', 'w') as file:
    file.write(response.text)

In [7]:
text = np.loadtxt("sample.txt")

In [8]:
count,edges = np.histogram(text)

bin_centers = (edges[:-1] + edges[1:]) / 2

for i in range(len(edges)-1):
    print(f"Bin number {i+1} - bin center : {bin_centers[i]} , count : {count[i]}")

Bin number 1 - bin center : -24.109006493430737 , count : 6
Bin number 2 - bin center : -11.150163704648554 , count : 23
Bin number 3 - bin center : 1.8086790841336278 , count : 52
Bin number 4 - bin center : 14.767521872915811 , count : 37
Bin number 5 - bin center : 27.726364661697996 , count : 16
Bin number 6 - bin center : 40.68520745048018 , count : 14
Bin number 7 - bin center : 53.64405023926236 , count : 13
Bin number 8 - bin center : 66.60289302804455 , count : 13
Bin number 9 - bin center : 79.56173581682673 , count : 13
Bin number 10 - bin center : 92.5205786056089 , count : 13


## Q3: Are you faster than numpy? No

Numpy of course has a standard deviation function, `np.std()`, but here we'll write our own that works on a 1-d array (vector).  The standard
deviation is a measure of the "width" of the distribution of numbers
in the vector.

Given an array, $a$, and an average $\bar{a}$, the standard deviation
is:
$$
\sigma = \left [ \frac{1}{N} \sum_{i=1}^N (a_i - \bar{a})^2 \right ]^{1/2}
$$

Write a function to calculate the standard deviation for an input array, `a`:

  * First compute the average of the elements in `a` to define $\bar{a}$
  * Next compute the sum over the squares of $a - \bar{a}$
  * Then divide the sum by the number of elements in the array
  * Finally take the square root (you can use `np.sqrt()`)
  
Test your function on a random array, and compare to the built-in `np.std()`. Check the runtime as well.

In [9]:
a  = np.linspace(0, 1000, 100000, endpoint=True)
a

array([0.00000e+00, 1.00001e-02, 2.00002e-02, ..., 9.99980e+02,
       9.99990e+02, 1.00000e+03])

In [10]:
def standard_dev (a):
    a_ = np.mean(a)
    sum_square = np.sum((a - a_) ** 2)
    variance = sum_square / len(a)

    return np.sqrt(variance)

In [11]:
# my function

import time


t0 = time.time()

stv_dev_mine = standard_dev(a)

t1 = time.time()
print("time elapsed: {} s".format(t1-t0))

time elapsed: 0.005008220672607422 s


In [12]:
# numpy

t0 = time.time()

stv_dev = np.std(a)

t1 = time.time()
print("time elapsed: {} s".format(t1-t0)) # faster

time elapsed: 0.004006624221801758 s
